on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          BRANCH_NAME="main-backMerge-${COMMIT_HASH}"
          git checkout -b ${BRANCH_NAME}
          gh pr create -B develop -H ${BRANCH_NAME} -t "Main backMerge" -b "sync main down to develop with updated permissions"
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
