name: Auto Create PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and checkout new branch
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME="main-backMerge-${COMMIT_HASH}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Create pull request
        run: |
          gh pr create --base develop --head ${{ github.actor }}:main-backMerge-${COMMIT_HASH} --title "Merge from main to develop" --body "Automated PR from main to develop."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
