on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create --base develop --head main --title "Main backMerge"
        env:
         GITHUB_TOKEN: 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
